/*
 * OneOf test
 * OneOf test
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: team@openapitools.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.V1EndpointPost200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1EndpointPost
     * @param stage  (required)
     * @param id  (optional)
     * @param type  (optional)
     * @param scope  (optional)
     * @param name  (optional)
     * @param description  (optional)
     * @param summary  (optional)
     * @param key  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointPostCall(String stage, String id, String type, String scope, String name, String description, String summary, String key, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/endpoint";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (id != null) {
            localVarFormParams.put("id", id);
        }

        if (type != null) {
            localVarFormParams.put("type", type);
        }

        if (scope != null) {
            localVarFormParams.put("scope", scope);
        }

        if (name != null) {
            localVarFormParams.put("name", name);
        }

        if (description != null) {
            localVarFormParams.put("description", description);
        }

        if (summary != null) {
            localVarFormParams.put("summary", summary);
        }

        if (key != null) {
            localVarFormParams.put("key", key);
        }

        if (stage != null) {
            localVarHeaderParams.put("Stage", localVarApiClient.parameterToString(stage));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded; charset=utf-8"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1EndpointPostValidateBeforeCall(String stage, String id, String type, String scope, String name, String description, String summary, String key, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'stage' is set
        if (stage == null) {
            throw new ApiException("Missing the required parameter 'stage' when calling v1EndpointPost(Async)");
        }

        return v1EndpointPostCall(stage, id, type, scope, name, description, summary, key, _callback);

    }

    /**
     * 
     * 
     * @param stage  (required)
     * @param id  (optional)
     * @param type  (optional)
     * @param scope  (optional)
     * @param name  (optional)
     * @param description  (optional)
     * @param summary  (optional)
     * @param key  (optional)
     * @return V1EndpointPost200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
     </table>
     */
    public V1EndpointPost200Response v1EndpointPost(String stage, String id, String type, String scope, String name, String description, String summary, String key) throws ApiException {
        ApiResponse<V1EndpointPost200Response> localVarResp = v1EndpointPostWithHttpInfo(stage, id, type, scope, name, description, summary, key);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param stage  (required)
     * @param id  (optional)
     * @param type  (optional)
     * @param scope  (optional)
     * @param name  (optional)
     * @param description  (optional)
     * @param summary  (optional)
     * @param key  (optional)
     * @return ApiResponse&lt;V1EndpointPost200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<V1EndpointPost200Response> v1EndpointPostWithHttpInfo(String stage, String id, String type, String scope, String name, String description, String summary, String key) throws ApiException {
        okhttp3.Call localVarCall = v1EndpointPostValidateBeforeCall(stage, id, type, scope, name, description, summary, key, null);
        Type localVarReturnType = new TypeToken<V1EndpointPost200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param stage  (required)
     * @param id  (optional)
     * @param type  (optional)
     * @param scope  (optional)
     * @param name  (optional)
     * @param description  (optional)
     * @param summary  (optional)
     * @param key  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1EndpointPostAsync(String stage, String id, String type, String scope, String name, String description, String summary, String key, final ApiCallback<V1EndpointPost200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1EndpointPostValidateBeforeCall(stage, id, type, scope, name, description, summary, key, _callback);
        Type localVarReturnType = new TypeToken<V1EndpointPost200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
