/*
 * OneOf test
 * OneOf test
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: team@openapitools.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RequestModelA;
import org.openapitools.client.model.RequestModelB;
import org.openapitools.client.model.RequestModelC;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-20T18:28:09.794317600+08:00[Asia/Singapore]")
public class V1EndpointPostRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(V1EndpointPostRequest.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!V1EndpointPostRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'V1EndpointPostRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RequestModelA> adapterRequestModelA = gson.getDelegateAdapter(this, TypeToken.get(RequestModelA.class));
            final TypeAdapter<RequestModelB> adapterRequestModelB = gson.getDelegateAdapter(this, TypeToken.get(RequestModelB.class));
            final TypeAdapter<RequestModelC> adapterRequestModelC = gson.getDelegateAdapter(this, TypeToken.get(RequestModelC.class));

            return (TypeAdapter<T>) new TypeAdapter<V1EndpointPostRequest>() {
                @Override
                public void write(JsonWriter out, V1EndpointPostRequest value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `RequestModelA`
                    if (value.getActualInstance() instanceof RequestModelA) {
                      JsonElement element = adapterRequestModelA.toJsonTree((RequestModelA)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `RequestModelB`
                    if (value.getActualInstance() instanceof RequestModelB) {
                      JsonElement element = adapterRequestModelB.toJsonTree((RequestModelB)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    // check if the actual instance is of the type `RequestModelC`
                    if (value.getActualInstance() instanceof RequestModelC) {
                      JsonElement element = adapterRequestModelC.toJsonTree((RequestModelC)value.getActualInstance());
                      elementAdapter.write(out, element);
                      return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: RequestModelA, RequestModelB, RequestModelC");
                }

                @Override
                public V1EndpointPostRequest read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize RequestModelA
                    try {
                      // validate the JSON object to see if any exception is thrown
                      RequestModelA.validateJsonElement(jsonElement);
                      actualAdapter = adapterRequestModelA;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'RequestModelA'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for RequestModelA failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'RequestModelA'", e);
                    }
                    // deserialize RequestModelB
                    try {
                      // validate the JSON object to see if any exception is thrown
                      RequestModelB.validateJsonElement(jsonElement);
                      actualAdapter = adapterRequestModelB;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'RequestModelB'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for RequestModelB failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'RequestModelB'", e);
                    }
                    // deserialize RequestModelC
                    try {
                      // validate the JSON object to see if any exception is thrown
                      RequestModelC.validateJsonElement(jsonElement);
                      actualAdapter = adapterRequestModelC;
                      match++;
                      log.log(Level.FINER, "Input data matches schema 'RequestModelC'");
                    } catch (Exception e) {
                      // deserialization failed, continue
                      errorMessages.add(String.format("Deserialization for RequestModelC failed with `%s`.", e.getMessage()));
                      log.log(Level.FINER, "Input data does not match schema 'RequestModelC'", e);
                    }

                    if (match == 1) {
                        V1EndpointPostRequest ret = new V1EndpointPostRequest();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for V1EndpointPostRequest: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public V1EndpointPostRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public V1EndpointPostRequest(RequestModelA o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public V1EndpointPostRequest(RequestModelB o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public V1EndpointPostRequest(RequestModelC o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RequestModelA", RequestModelA.class);
        schemas.put("RequestModelB", RequestModelB.class);
        schemas.put("RequestModelC", RequestModelC.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return V1EndpointPostRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * RequestModelA, RequestModelB, RequestModelC
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof RequestModelA) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof RequestModelB) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof RequestModelC) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be RequestModelA, RequestModelB, RequestModelC");
    }

    /**
     * Get the actual instance, which can be the following:
     * RequestModelA, RequestModelB, RequestModelC
     *
     * @return The actual instance (RequestModelA, RequestModelB, RequestModelC)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RequestModelA`. If the actual instance is not `RequestModelA`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RequestModelA`
     * @throws ClassCastException if the instance is not `RequestModelA`
     */
    public RequestModelA getRequestModelA() throws ClassCastException {
        return (RequestModelA)super.getActualInstance();
    }
    /**
     * Get the actual instance of `RequestModelB`. If the actual instance is not `RequestModelB`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RequestModelB`
     * @throws ClassCastException if the instance is not `RequestModelB`
     */
    public RequestModelB getRequestModelB() throws ClassCastException {
        return (RequestModelB)super.getActualInstance();
    }
    /**
     * Get the actual instance of `RequestModelC`. If the actual instance is not `RequestModelC`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RequestModelC`
     * @throws ClassCastException if the instance is not `RequestModelC`
     */
    public RequestModelC getRequestModelC() throws ClassCastException {
        return (RequestModelC)super.getActualInstance();
    }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to V1EndpointPostRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    // validate oneOf schemas one by one
    int validCount = 0;
    ArrayList<String> errorMessages = new ArrayList<>();
    // validate the json string with RequestModelA
    try {
      RequestModelA.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for RequestModelA failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with RequestModelB
    try {
      RequestModelB.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for RequestModelB failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    // validate the json string with RequestModelC
    try {
      RequestModelC.validateJsonElement(jsonElement);
      validCount++;
    } catch (Exception e) {
      errorMessages.add(String.format("Deserialization for RequestModelC failed with `%s`.", e.getMessage()));
      // continue to the next one
    }
    if (validCount != 1) {
      throw new IOException(String.format("The JSON string is invalid for V1EndpointPostRequest with oneOf schemas: RequestModelA, RequestModelB, RequestModelC. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
    }
  }

 /**
  * Create an instance of V1EndpointPostRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of V1EndpointPostRequest
  * @throws IOException if the JSON string is invalid with respect to V1EndpointPostRequest
  */
  public static V1EndpointPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V1EndpointPostRequest.class);
  }

 /**
  * Convert an instance of V1EndpointPostRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

